apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # no permite que tengamos pods inactivos durante la actualizacion
      maxSurge: 1 # permite un pod adcional termporalmente durante el proceso de actualizacion
  template:
    metadata:
      labels:
        app: my-app-nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        resources:  
          requests:
            memory: "8Mi"
            cpu: "10m" # 1% del nucleo de cpu
          limits:
            memory: "16Mi"
            cpu: "50m" #5 % del nucleo de cpu
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-nginx
spec:
  selector:
    app: my-app-nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083