apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:  
        requests:
          memory: "8Mi"
          cpu: "10m" # 1% del nucleo de cpu
        limits:
          memory: "16Mi"
          cpu: "50m" #5 % del nucleo de cpu
      ports:
      - containerPort: 80
    